// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import Image from 'next/image'
// import Header from './components/Header'
// import { Button } from '@/components/ui/button'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
        
//           <header className="flex justify-between items-center p-4 gap-4 h-16">
//             <Image src={'/logo.svg'} alt='logo' width={180} height={100}/>
//           <div className='flex gap-6 items-center justify-end'>
//               <Button>Dashboard</Button>
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton>
//                 <button className="bg-[#6c47ff] text-white rounded-full font-small text-sm sm:text-base md:h-9 sm:h-12 px-2 sm:px-5 cursor-pointer">
//                   Sign Up
//                 </button>
//               </SignUpButton>
//             </SignedOut>

//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </div>
//           </header>

//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import Provider from './Provider' // Add this import

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Provider> 
            <header className="flex justify-between items-center p-4 gap-4 h-16">
              <Image src={'/logo.svg'} alt='logo' width={180} height={100}/>
              <div className='flex gap-6 items-center justify-end'>
                <Button>Dashboard</Button>
                <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-small text-sm sm:text-base md:h-9 sm:h-12 px-2 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>

                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </header>

            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}